### ISSUE TITLE
Module sklearn.cross_validation deprecated

### ISSUE THREAD

**Issue by geoperez** [JerryKurata/MachineLearningWithPython#4]
I got a notice about the cross_validation module will be removed soon, what is the alternative for data splitting?

`Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)`

**Comment by nickforce** [comment]
@geoperez 
replace `from sklearn.cross_validation` with the new import `from sklearn.model_selection`
